name: Test
on:
  [push]
jobs:
  test-api:
    runs-on:ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      run: npm run apitests